// Copyright (c) Tzvetan Mikov.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
//
// Ties the vendored hermes-parser-native JavaScript package to the hermes/
// submodule.
//
// The addon derives a node-kind hash from the submodule's ESTree.def at
// compile time (external/hermes-parser-native/napi/KindHash.h) and stamps it
// into every serialized parse result. The JavaScript side carries its own
// copy of that number, generated by scripts/genKindHash.js and committed as
// external/hermes-parser-native/package/{src,dist}/HermesParserKindHash.js,
// and refuses to deserialize a container whose stamp disagrees.
//
// Nothing else in the offline test suite notices when the two drift apart: a
// hermes/ submodule bump that touches ESTree.def changes the C++ side only,
// and the vendored package then fails at run time with a "node-kind table
// mismatch" error. The only other check is examples/flow-bundler, which is
// opt-in, Release-only, and skipped unless someone has run `npm install`.
//
// So this test recomputes the hash from the submodule's definitions and
// requires the committed JavaScript to contain that exact number. Both the
// Flow source under src/ and the transpiled dist/ that actually runs are
// checked, because regenerating one without the other is its own kind of
// desync.
//
// This file is ours, not part of the verbatim copy in
// unittests/HermesParserNative/, and it is deleted along with the rest of the
// vendored arrangement.

#include "KindHash.h"

#include <gtest/gtest.h>

#include <cctype>
#include <cstdio>
#include <string>

#ifndef HPN_KIND_HASH_SRC_JS
#error "HPN_KIND_HASH_SRC_JS must be defined by the build"
#endif
#ifndef HPN_KIND_HASH_DIST_JS
#error "HPN_KIND_HASH_DIST_JS must be defined by the build"
#endif

namespace {

/// \return the entire contents of \p path, or an empty optional-ish result
/// signalled by \p ok being set to false.
std::string readWholeFile(const char *path, bool &ok) {
  ok = false;
  std::FILE *f = std::fopen(path, "rb");
  if (!f)
    return std::string{};

  std::string contents;
  char buf[4096];
  size_t n;
  while ((n = std::fread(buf, 1, sizeof(buf), f)) > 0)
    contents.append(buf, n);

  ok = std::ferror(f) == 0;
  std::fclose(f);
  return contents;
}

/// \return true if \p needle occurs in \p haystack as a maximal run of
/// decimal digits, i.e. not as a substring of a longer number. Matching a
/// whole token rather than the raw substring is what makes 2417426143 fail to
/// match 24174261430 or 12417426143.
bool containsNumberToken(
    const std::string &haystack,
    const std::string &needle) {
  for (size_t pos = haystack.find(needle); pos != std::string::npos;
       pos = haystack.find(needle, pos + 1)) {
    bool digitBefore = pos > 0 && isdigit((unsigned char)haystack[pos - 1]);
    size_t after = pos + needle.size();
    bool digitAfter =
        after < haystack.size() && isdigit((unsigned char)haystack[after]);
    if (!digitBefore && !digitAfter)
      return true;
  }
  return false;
}

/// Assert that \p path exists and mentions \p expected as a standalone number.
void expectFilePinsHash(const char *path, const std::string &expected) {
  bool ok = false;
  std::string contents = readWholeFile(path, ok);
  ASSERT_TRUE(ok) << "cannot read " << path;

  EXPECT_TRUE(containsNumberToken(contents, expected))
      << path << " does not contain the node-kind hash " << expected
      << " that the addon computes from the hermes/ submodule's ESTree.def.\n"
      << "The vendored hermes-parser-native package and the submodule have "
         "drifted apart; the package would fail at parse time with a "
         "node-kind table mismatch.\n"
      << "Regenerate it with:\n"
      << "  cmake --build <build-dir> --target hermes-parser-native-dist\n"
      << "and commit the updated "
         "external/hermes-parser-native/package/{src,dist}/"
         "HermesParserKindHash.js.";
}

TEST(HermesParserKindHashSyncTest, VendoredSourceMatchesSubmodule) {
  expectFilePinsHash(
      HPN_KIND_HASH_SRC_JS, std::to_string(hermes::computeKindHash()));
}

TEST(HermesParserKindHashSyncTest, VendoredDistMatchesSubmodule) {
  expectFilePinsHash(
      HPN_KIND_HASH_DIST_JS, std::to_string(hermes::computeKindHash()));
}

} // namespace
