#!/usr/bin/env python3
# Copyright (c) Tzvetan Mikov.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Generate the embedded module registry C++ file.

Usage: gen-embedded-registry.py <manifest> <inc_dir> <output.cpp>

Reads the module manifest (embedded-modules.txt) and generates a C++
source file that:
  - #includes each <safe_id>.hbc.inc as a static byte array
  - Builds a lookup table mapping module ID -> (data, size, isBootstrap)
  - Provides findEmbeddedModule(id) via binary search
"""

import os
import sys


def safe_id(module_id):
    """Convert a module ID to a C-safe identifier.

    e.g. 'internal/errors' -> 'internal__errors'
         'stream/promises' -> 'stream__promises'
         'internal/streams/add-abort-signal' -> 'internal__streams__add_abort_signal'
    """
    return module_id.replace("/", "__").replace("-", "_")


def main():
    if len(sys.argv) != 4:
        print(
            "Usage: gen-embedded-registry.py <manifest> <inc_dir> <output.cpp>",
            file=sys.stderr,
        )
        sys.exit(1)

    manifest_path = sys.argv[1]
    inc_dir = sys.argv[2]
    output_path = sys.argv[3]

    modules = []  # list of (module_id, is_bootstrap)

    with open(manifest_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("@bootstrap "):
                mod_id = line[len("@bootstrap "):].strip()
                modules.append((mod_id, True))
            else:
                modules.append((line, False))

    lines = []
    lines.append("// AUTO-GENERATED by gen-embedded-registry.py. DO NOT EDIT.")
    lines.append("")
    lines.append(
        '#include "hermes/node-compat/embedded-modules/embedded_modules.h"'
    )
    lines.append("")
    lines.append("#include <algorithm>")
    lines.append("#include <cstring>")
    lines.append("")
    lines.append("namespace hermes {")
    lines.append("namespace node_compat {")
    lines.append("")

    # Emit byte arrays.
    for mod_id, is_bootstrap in modules:
        sid = safe_id(mod_id)
        inc_file = sid + ".hbc.inc"
        lines.append(
            "alignas(4) static const uint8_t data_%s[] = {" % sid
        )
        lines.append('#include "%s"' % inc_file)
        lines.append("};")
        lines.append("")

    # Emit module table sorted by ID for binary search.
    sorted_modules = sorted(modules, key=lambda m: m[0])
    lines.append("static const EmbeddedModule kModules[] = {")
    for mod_id, is_bootstrap in sorted_modules:
        sid = safe_id(mod_id)
        bootstrap_str = "true" if is_bootstrap else "false"
        lines.append(
            '    {"%s", data_%s, sizeof(data_%s), %s},'
            % (mod_id, sid, sid, bootstrap_str)
        )
    lines.append("};")
    lines.append("")
    lines.append(
        "static const size_t kModuleCount = sizeof(kModules) / sizeof(kModules[0]);"
    )
    lines.append("")

    # Emit binary search lookup.
    lines.append("const EmbeddedModule *findEmbeddedModule(const char *id) {")
    lines.append("  auto it = std::lower_bound(")
    lines.append("      kModules, kModules + kModuleCount, id,")
    lines.append("      [](const EmbeddedModule &m, const char *key) {")
    lines.append("        return std::strcmp(m.id, key) < 0;")
    lines.append("      });")
    lines.append("  if (it != kModules + kModuleCount && std::strcmp(it->id, id) == 0)")
    lines.append("    return it;")
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace node_compat")
    lines.append("} // namespace hermes")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
