#!/usr/bin/env python3
# Copyright (c) Tzvetan Mikov.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Generate the NATIVE embedded module registry.

Usage: gen-native-registry.py <manifest> <unit-map> <output.cpp>

Emits the same findEmbeddedModule() symbol gen-embedded-registry.py emits,
over a table of Static Hermes unit creators instead of bytecode arrays. A
build-native link names this archive ahead of the merged kit archive, so the
linker resolves findEmbeddedModule here and never pulls the bytecode member --
which is what keeps 2.1 MB of built-in bytecode out of a native artifact.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from embedded_module_ids import parse_manifest, unit_name, validate


def check_cmake_names(modules, map_path):
    """Refuse to emit if CMake and Python disagree about any unit name.

    CMake derives a unit name inside its own loops, before the combined
    manifest exists, so it cannot ask this module for one. It records what it
    used instead, and this compares the two sets. Without the check, extending
    safe_id() here -- which is what its own diagnostic tells you to do --
    would have the registry declare sh_export_<new> while shermes emitted
    sh_export_<old>, and the link would fail naming a unit nobody wrote.
    """
    recorded = {}
    with open(map_path) as f:
        for n, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            module_id, _, name = line.partition(" ")
            if not name:
                sys.exit("%s:%d: expected '<module id> <unit name>'"
                         % (map_path, n))
            if module_id in recorded:
                sys.exit("%s:%d: %r recorded twice" % (map_path, n, module_id))
            recorded[module_id] = name

    ours = {module_id: unit_name(module_id) for module_id, _ in modules}
    missing = sorted(set(ours) - set(recorded))
    extra = sorted(set(recorded) - set(ours))
    if missing:
        sys.exit("CMake compiled no unit for these manifest modules: %s"
                 % ", ".join(missing))
    if extra:
        sys.exit("CMake compiled units for modules the manifest does not "
                 "list: %s" % ", ".join(extra))
    for module_id in sorted(ours):
        if ours[module_id] != recorded[module_id]:
            sys.exit(
                "unit name disagreement for %r: CMake used %r, "
                "embedded_module_ids.unit_name() gives %r. Both derivations "
                "must match or the registry declares a symbol shermes never "
                "emitted." % (module_id, recorded[module_id], ours[module_id]))


def main():
    if len(sys.argv) != 4:
        print(
            "Usage: gen-native-registry.py <manifest> <unit-map> <output.cpp>",
            file=sys.stderr,
        )
        sys.exit(1)

    modules = parse_manifest(sys.argv[1])
    validate(modules)
    check_cmake_names(modules, sys.argv[2])

    out = []
    w = out.append
    w("// AUTO-GENERATED by gen-native-registry.py. DO NOT EDIT.")
    w("")
    w('#include "hermes/node-compat/embedded-modules/embedded_modules.h"')
    w("")
    w("#include <algorithm>")
    w("#include <cstring>")
    w("")
    # Global scope, C linkage: `shermes -exported-unit=X` emits
    # `SHUnit *sh_export_X(void)` from a C file.
    w('extern "C" {')
    for module_id, _ in modules:
        w("SHUnit *sh_export_%s(void);" % unit_name(module_id))
    w("}")
    w("")
    # Also global scope and also C linkage, and both matter. build-native
    # passes -Wl,-u,<prefix>hermesNodeNativeBuiltinsMarker, which names an
    # UNMANGLED symbol: a C++ definition would be mangled and every native
    # link would fail. It sits in this translation unit on purpose -- rooting
    # it is what extracts this archive member, and therefore what makes this
    # file's findEmbeddedModule the one that wins.
    w("/// Rooted with -Wl,-u by a build-native link. Its only job is to")
    w("/// exist: if this archive is missing from the link line the marker")
    w("/// is undefined and the link fails by name, instead of silently")
    w("/// falling through to the bytecode registry in the merged kit")
    w("/// archive and producing a working, interpreted binary.")
    w('extern "C" const char hermesNodeNativeBuiltinsMarker = 1;')
    w("")
    w("namespace hermes {")
    w("namespace node_compat {")
    w("")
    w("static const EmbeddedModule kModules[] = {")
    for module_id, is_bootstrap in sorted(modules, key=lambda m: m[0]):
        w(
            '    {"%s", nullptr, 0, sh_export_%s, %s},'
            % (module_id, unit_name(module_id),
               "true" if is_bootstrap else "false")
        )
    w("};")
    w("")
    w("static const size_t kModuleCount = "
      "sizeof(kModules) / sizeof(kModules[0]);")
    w("")
    w("const EmbeddedModule *findEmbeddedModule(const char *id) {")
    w("  auto it = std::lower_bound(")
    w("      kModules, kModules + kModuleCount, id,")
    w("      [](const EmbeddedModule &m, const char *key) {")
    w("        return std::strcmp(m.id, key) < 0;")
    w("      });")
    w("  if (it != kModules + kModuleCount && "
      "std::strcmp(it->id, id) == 0)")
    w("    return it;")
    w("  return nullptr;")
    w("}")
    w("")
    w("} // namespace node_compat")
    w("} // namespace hermes")
    w("")

    with open(sys.argv[3], "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
